export interface Brand {
  name: string;
  slug: string;
  letter: string;
  tagline: string;
  image: string;
  category: string;
  country: string;
  founded: string;
  description: string;
}

export const BRANDS: Brand[] = [
  // A
  {
    name: "ACP",
    slug: "acp",
    letter: "A",
    tagline: "Faster Cooking. Better Results.",
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=500&q=80",
    category: "Cooking Equipment",
    country: "USA",
    founded: "1978",
    description: "ACP is a leading manufacturer of commercial microwave and speed cooking ovens for foodservice operations.",
  },
  {
    name: "American Dish Service",
    slug: "american-dish-service",
    letter: "A",
    tagline: "Commercial Warewashing Solutions",
    image: "https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=500&q=80",
    category: "Warewashing",
    country: "USA",
    founded: "1959",
    description: "ADS manufactures high-quality commercial dishwashers and warewashing systems for restaurants and institutions.",
  },
  {
    name: "Amerikooler",
    slug: "amerikooler",
    letter: "A",
    tagline: "Drink & Cool Further",
    image: "https://images.unsplash.com/photo-1586770945935-8a08b0e0e1d4?w=500&q=80",
    category: "Refrigeration",
    country: "USA",
    founded: "1985",
    description: "Amerikooler specializes in walk-in coolers and freezers for commercial foodservice applications.",
  },
  {
    name: "AMgood",
    slug: "amgood",
    letter: "A",
    tagline: "Quality Equipment, Better Kitchens",
    image: "https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=500&q=80",
    category: "Kitchen Equipment",
    country: "USA",
    founded: "2002",
    description: "AMgood provides commercial food preparation and kitchen storage solutions for modern restaurants.",
  },
  {
    name: "Arctic Air",
    slug: "arctic-air",
    letter: "A",
    tagline: "Reliable Commercial Refrigeration",
    image: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=500&q=80",
    category: "Refrigeration",
    country: "USA",
    founded: "1990",
    description: "Arctic Air delivers durable and energy-efficient commercial refrigeration equipment at competitive prices.",
  },
  {
    name: "Astra",
    slug: "astra",
    letter: "A",
    tagline: "Precision Cold Storage",
    image: "https://images.unsplash.com/photo-1606312619070-d48b4c652a52?w=500&q=80",
    category: "Refrigeration",
    country: "USA",
    founded: "1995",
    description: "Astra manufactures modular walk-in coolers and custom refrigeration solutions for commercial use.",
  },
  {
    name: "Atosa",
    slug: "atosa",
    letter: "A",
    tagline: "Smart Refrigeration Solutions",
    image: "https://images.unsplash.com/photo-1620360289473-d9e9a36aaa77?w=500&q=80",
    category: "Refrigeration",
    country: "USA",
    founded: "2010",
    description: "Atosa offers a full line of commercial refrigeration, cooking, and food preparation equipment.",
  },
  // B
  {
    name: "BakeMax",
    slug: "bakemax",
    letter: "B",
    tagline: "Baking Perfection Every Time",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&q=80",
    category: "Bakery Equipment",
    country: "USA",
    founded: "1998",
    description: "BakeMax designs professional bakery equipment including dough sheeters, dividers, and ovens.",
  },
  {
    name: "Beverage-Air",
    slug: "beverage-air",
    letter: "B",
    tagline: "Engineered for Foodservice",
    image: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=500&q=80",
    category: "Refrigeration",
    country: "USA",
    founded: "1944",
    description: "Beverage-Air is a premier manufacturer of commercial refrigeration equipment for the foodservice industry.",
  },
  {
    name: "Blendtec",
    slug: "blendtec",
    letter: "B",
    tagline: "Will It Blend?",
    image: "https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=500&q=80",
    category: "Food Preparation",
    country: "USA",
    founded: "1975",
    description: "Blendtec makes powerful commercial blenders trusted by cafes, restaurants, and smoothie bars worldwide.",
  },
  {
    name: "Bunn",
    slug: "bunn",
    letter: "B",
    tagline: "The World's Greatest Beverages",
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=500&q=80",
    category: "Beverage Equipment",
    country: "USA",
    founded: "1957",
    description: "Bunn manufactures commercial beverage equipment including coffee brewers, tea systems, and dispensers.",
  },
  // C
  {
    name: "Cambro",
    slug: "cambro",
    letter: "C",
    tagline: "Products That Perform",
    image: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=500&q=80",
    category: "Storage & Transport",
    country: "USA",
    founded: "1951",
    description: "Cambro manufactures industry-leading foodservice storage, transport, and display solutions.",
  },
  {
    name: "Continental",
    slug: "continental",
    letter: "C",
    tagline: "Commercial Refrigeration Leaders",
    image: "https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=500&q=80",
    category: "Refrigeration",
    country: "USA",
    founded: "1968",
    description: "Continental Refrigerator produces high-quality commercial reach-in and prep-table refrigerators.",
  },
  {
    name: "Cuisinart",
    slug: "cuisinart",
    letter: "C",
    tagline: "Savor the Good Life",
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500&q=80",
    category: "Food Preparation",
    country: "USA",
    founded: "1971",
    description: "Cuisinart offers premium commercial food processors, blenders, and kitchen appliances.",
  },
  // D
  {
    name: "Delfield",
    slug: "delfield",
    letter: "D",
    tagline: "Commercial Refrigeration Experts",
    image: "https://images.unsplash.com/photo-1620360289473-d9e9a36aaa77?w=500&q=80",
    category: "Refrigeration",
    country: "USA",
    founded: "1949",
    description: "Delfield manufactures custom commercial refrigeration solutions for foodservice operations of all sizes.",
  },
  {
    name: "Duke",
    slug: "duke",
    letter: "D",
    tagline: "Holding & Serving Solutions",
    image: "https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=500&q=80",
    category: "Cooking Equipment",
    country: "USA",
    founded: "1929",
    description: "Duke Manufacturing provides commercial foodservice holding, warming, and serving equipment.",
  },
  // E
  {
    name: "Eurodib",
    slug: "eurodib",
    letter: "E",
    tagline: "European Quality, North American Value",
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=500&q=80",
    category: "Kitchen Equipment",
    country: "Canada",
    founded: "1985",
    description: "Eurodib distributes a wide range of commercial cooking, refrigeration, and food prep equipment.",
  },
  // F
  {
    name: "Fagor",
    slug: "fagor",
    letter: "F",
    tagline: "Professional Kitchen Solutions",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&q=80",
    category: "Cooking Equipment",
    country: "Spain",
    founded: "1956",
    description: "Fagor Professional designs and manufactures commercial cooking equipment for the hospitality industry.",
  },
  {
    name: "Follett",
    slug: "follett",
    letter: "F",
    tagline: "Ice & Chilled Solutions",
    image: "https://images.unsplash.com/photo-1586770945935-8a08b0e0e1d4?w=500&q=80",
    category: "Ice Machines",
    country: "USA",
    founded: "1948",
    description: "Follett manufactures commercial ice and water dispensers, ice storage, and transport systems.",
  },
  // G
  {
    name: "Garland",
    slug: "garland",
    letter: "G",
    tagline: "Commercial Cooking Performance",
    image: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=500&q=80",
    category: "Cooking Equipment",
    country: "USA",
    founded: "1864",
    description: "Garland is one of the oldest and most trusted names in commercial cooking and range equipment.",
  },
  {
    name: "Globe",
    slug: "globe",
    letter: "G",
    tagline: "Food Service Equipment",
    image: "https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=500&q=80",
    category: "Food Preparation",
    country: "USA",
    founded: "1887",
    description: "Globe Food Equipment manufactures commercial slicers, mixers, and food preparation equipment.",
  },
  // H
  {
    name: "Hatco",
    slug: "hatco",
    letter: "H",
    tagline: "Food Equipment That Works",
    image: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=500&q=80",
    category: "Holding & Display",
    country: "USA",
    founded: "1950",
    description: "Hatco Corporation manufactures commercial food warming, toasting, and display equipment.",
  },
  {
    name: "Hoshizaki",
    slug: "hoshizaki",
    letter: "H",
    tagline: "Simply the Best",
    image: "https://images.unsplash.com/photo-1606312619070-d48b4c652a52?w=500&q=80",
    category: "Ice Machines",
    country: "Japan",
    founded: "1947",
    description: "Hoshizaki is a world leader in commercial ice machines, refrigerators, and freezers.",
  },
  // I
  {
    name: "Imperial",
    slug: "imperial",
    letter: "I",
    tagline: "Heavy Duty Commercial Ranges",
    image: "https://images.unsplash.com/photo-1620360289473-d9e9a36aaa77?w=500&q=80",
    category: "Cooking Equipment",
    country: "USA",
    founded: "1957",
    description: "Imperial Range manufactures heavy-duty commercial ranges, fryers, and cooking equipment.",
  },
  // J
  {
    name: "John Boos",
    slug: "john-boos",
    letter: "J",
    tagline: "American Craftsmanship Since 1887",
    image: "https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=500&q=80",
    category: "Kitchen Equipment",
    country: "USA",
    founded: "1887",
    description: "John Boos manufactures premium butcher blocks, stainless steel tables, and sinks for commercial kitchens.",
  },
  // K
  {
    name: "Kairak",
    slug: "kairak",
    letter: "K",
    tagline: "Commercial Refrigeration",
    image: "https://images.unsplash.com/photo-1586770945935-8a08b0e0e1d4?w=500&q=80",
    category: "Refrigeration",
    country: "USA",
    founded: "1972",
    description: "Kairak produces reliable commercial refrigeration equipment for the foodservice industry.",
  },
  // L
  {
    name: "Lang",
    slug: "lang",
    letter: "L",
    tagline: "Commercial Cooking Solutions",
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=500&q=80",
    category: "Cooking Equipment",
    country: "USA",
    founded: "1941",
    description: "Lang Manufacturing produces commercial griddles, ranges, and other cooking equipment.",
  },
  {
    name: "Lincat",
    slug: "lincat",
    letter: "L",
    tagline: "Professional Catering Equipment",
    image: "https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=500&q=80",
    category: "Cooking Equipment",
    country: "UK",
    founded: "1975",
    description: "Lincat is the UK's leading manufacturer of commercial catering equipment for the hospitality sector.",
  },
  // M
  {
    name: "Manitowoc",
    slug: "manitowoc",
    letter: "M",
    tagline: "Ice. Perfected.",
    image: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=500&q=80",
    category: "Ice Machines",
    country: "USA",
    founded: "1902",
    description: "Manitowoc Foodservice is a global leader in commercial ice machines and refrigeration equipment.",
  },
  {
    name: "Merrychef",
    slug: "merrychef",
    letter: "M",
    tagline: "Speed Oven Specialists",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&q=80",
    category: "Cooking Equipment",
    country: "UK",
    founded: "1948",
    description: "Merrychef is a world leader in high-speed combination ovens for commercial foodservice operations.",
  },
  // N
  {
    name: "Nemco",
    slug: "nemco",
    letter: "N",
    tagline: "Food Service Made Simple",
    image: "https://images.unsplash.com/photo-1606312619070-d48b4c652a52?w=500&q=80",
    category: "Food Preparation",
    country: "USA",
    founded: "1976",
    description: "Nemco manufactures specialty food service equipment including food cutters, steamers, and warmers.",
  },
  // O
  {
    name: "Omega",
    slug: "omega",
    letter: "O",
    tagline: "Commercial Equipment Excellence",
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=500&q=80",
    category: "Kitchen Equipment",
    country: "USA",
    founded: "1988",
    description: "Omega produces commercial kitchen equipment designed for durability and performance.",
  },
  // P
  {
    name: "Pitco",
    slug: "pitco",
    letter: "P",
    tagline: "Fryers for the World",
    image: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=500&q=80",
    category: "Cooking Equipment",
    country: "USA",
    founded: "1918",
    description: "Pitco is one of the world's leading manufacturers of commercial fryers for the foodservice industry.",
  },
  {
    name: "Prince Castle",
    slug: "prince-castle",
    letter: "P",
    tagline: "Serving the QSR Industry",
    image: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=500&q=80",
    category: "Cooking Equipment",
    country: "USA",
    founded: "1949",
    description: "Prince Castle manufactures specialty equipment for quick-service restaurant operations.",
  },
  // R
  {
    name: "Rational",
    slug: "rational",
    letter: "R",
    tagline: "The Future of Cooking",
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=500&q=80",
    category: "Cooking Equipment",
    country: "Germany",
    founded: "1973",
    description: "Rational is the world market leader in thermal food preparation for professional kitchens.",
  },
  {
    name: "Robot Coupe",
    slug: "robot-coupe",
    letter: "R",
    tagline: "Professional Food Processors",
    image: "https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=500&q=80",
    category: "Food Preparation",
    country: "France",
    founded: "1961",
    description: "Robot Coupe invented the food processor and remains the global leader in professional food preparation equipment.",
  },
  // S
  {
    name: "Scotsman",
    slug: "scotsman",
    letter: "S",
    tagline: "The Ice Machine People",
    image: "https://images.unsplash.com/photo-1586770945935-8a08b0e0e1d4?w=500&q=80",
    category: "Ice Machines",
    country: "USA",
    founded: "1950",
    description: "Scotsman manufactures premium commercial ice machines, ice storage bins, and dispensers.",
  },
  {
    name: "Southbend",
    slug: "southbend",
    letter: "S",
    tagline: "Heavy Duty Cooking Equipment",
    image: "https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=500&q=80",
    category: "Cooking Equipment",
    country: "USA",
    founded: "1898",
    description: "Southbend manufactures heavy-duty commercial ranges, ovens, and cooking suites for demanding kitchens.",
  },
  // T
  {
    name: "True Refrigeration",
    slug: "true-refrigeration",
    letter: "T",
    tagline: "Refrigeration You Can Trust",
    image: "https://images.unsplash.com/photo-1620360289473-d9e9a36aaa77?w=500&q=80",
    category: "Refrigeration",
    country: "USA",
    founded: "1945",
    description: "True is the world's leading manufacturer of commercial refrigerators, freezers, and coolers.",
  },
  {
    name: "Turbochef",
    slug: "turbochef",
    letter: "T",
    tagline: "Speed Cooking Technology",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&q=80",
    category: "Cooking Equipment",
    country: "USA",
    founded: "1991",
    description: "TurboChef Technologies specializes in high-speed commercial ovens that cook up to 15x faster.",
  },
  // U
  {
    name: "Ultrafryer",
    slug: "ultrafryer",
    letter: "U",
    tagline: "Superior Frying Solutions",
    image: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=500&q=80",
    category: "Cooking Equipment",
    country: "USA",
    founded: "1969",
    description: "Ultrafryer Systems produces high-performance commercial fryers for restaurants and food chains.",
  },
  // V
  {
    name: "Vitamix",
    slug: "vitamix",
    letter: "V",
    tagline: "Making the World a Better Place",
    image: "https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=500&q=80",
    category: "Food Preparation",
    country: "USA",
    founded: "1921",
    description: "Vitamix manufactures professional-grade commercial blenders trusted by chefs and beverage professionals.",
  },
  {
    name: "Vulcan",
    slug: "vulcan",
    letter: "V",
    tagline: "Commercial Cooking Equipment",
    image: "https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=500&q=80",
    category: "Cooking Equipment",
    country: "USA",
    founded: "1865",
    description: "Vulcan is a leading manufacturer of commercial cooking equipment including ranges, ovens, and fryers.",
  },
  // W
  {
    name: "Waring",
    slug: "waring",
    letter: "W",
    tagline: "Blending Innovation Since 1937",
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=500&q=80",
    category: "Food Preparation",
    country: "USA",
    founded: "1937",
    description: "Waring Commercial manufactures professional blenders, food processors, and kitchen appliances.",
  },
  {
    name: "Wells",
    slug: "wells",
    letter: "W",
    tagline: "Warming & Holding Solutions",
    image: "https://images.unsplash.com/photo-1606312619070-d48b4c652a52?w=500&q=80",
    category: "Holding & Display",
    country: "USA",
    founded: "1920",
    description: "Wells Manufacturing produces commercial hot food holding equipment, warmers, and fryers.",
  },
];

export const ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");

export const getBrandsByLetter = () => {
  const map: Record<string, Brand[]> = {};
  BRANDS.forEach((b) => {
    if (!map[b.letter]) map[b.letter] = [];
    map[b.letter].push(b);
  });
  return map;
};

export const getActiveLette = () => {
  const used = new Set(BRANDS.map((b) => b.letter));
  return used;
};
